namespace Eloi
{
    public class E_InCodeNameCollection
    {

        public static string[] m_disneyCharacter = new string[]{
    "Alberto Scorfano  ",
"Abby Mallard  ",
"Abigail Gabble  ",
"Abu  ",
"Achilles  ",
"Adella  ",
"Adelaide  ",
"Adorabeezle Winterpop  ",
"The Agent  ",
"Agent Wendy Pleakley  ",
"Ajax the Gorilla  ",
"Akela  ",
"Al the Alligator  ",
"Aladar  ",
"Aladdin  ",
"Alameda Slim  ",
"Alan-a-Dale  ",
"Alana  ",
"Albus Duckweed  ",
"Alcmene  ",
"Alfonso Dolittle  ",
"Alice  ",
"Alice Bluebonnet  ",
"Alice's Sister  ",
"Amelia Gabble  ",
"Amity Blight  ",
"Amos Slade  ",
"Amphitryon  ",
"Anastasia Tremaine  ",
"Andrina  ",
"Andromeda  ",
"Angie Diaz  ",
"Angus MacBadger  ",
"Animal  ",
"Anita Radcliffe  ",
"Anna  ",
"Anne Boonchuy  ",
"Annette  ",
"April  ",
"Apollo  ",
"Aquata  ",
"Aracuan Bird  ",
"The Archdeacon  ",
"Archimedes Q. Porter  ",
"Archimedes  ",
"Ariel  ",
"Arista  ",
"Armoire  ",
"Arthur/Wart  ",
"Arthur  ",
"Assistant Mayor Dawn Bellwether  ",
"Atka  ",
"Atropos  ",
"Attina  ",
"Audrey the Chicken  ",
"Audrey Ramirez  ",
"Augustus  Porter  ",
"Aunt Sarah  ",
"Aunt Siqiniq  ",
"Aunt Taqqiq  ",
"Aurora  ",
"Axe  ",
"B[edit]  ",
"B.E.N.  ",
"Babette  ",
"Baby Red Bird  ",
"Baby Sinclair  ",
"Babyface Beagle  ",
"Backwoods Beagle  ",
"Bacon Beagle  ",
"Baggy Beagle  ",
"Bagheera  ",
"Baileywick  ",
"Baker  ",
"Baker  ",
"Ballerina  ",
"Baloo Bear  ",
"Bambi  ",
"Bambi's Mother  ",
"Banzai  ",
"Bankjob Beagle  ",
"Bartholomew  ",
"Barley Lightfoot  ",
"Bashful  ",
"Basil of Baker Street  ",
"Bat Queen  ",
"Baylene  ",
"Baymax  ",
"Beaker  ",
"Bear  ",
"Beary Barrington  ",
"Beast  ",
"Beaver  ",
"Becky  ",
"Bella  ",
"Belle  ",
"Ben  ",
"Ben Ali Gator  ",
"Benjamin Clawhauser  ",
"Benny  ",
"Bent-Tail the Coyote  ",
"Bent-Tail Junior  ",
"Bentina Beakley  ",
"Beret Girl  ",
"Berlioz  ",
"Bernard  ",
"Big Al  ",
"Big Bad Wolf  ",
"Big Mama  ",
"Bigtime Beagle  ",
"Bill Green  ",
"Bill the Lizard  ",
"Billy Boss  ",
"Billy Bones  ",
"Bimbette  ",
"Binkie Muddlefoot  ",
"Binky Beagle  ",
"Black Bart  ",
"Blarney  ",
"Blake  ",
"Blaze  ",
"Blue Fairy  ",
"Bobble  ",
"Bog  ",
"Bolt  ",
"Bomber Beagle  ",
"Bonnie Hopps  ",
"Bookseller  ",
"Boomer  ",
"Boone Wiseman  ",
"Bonkers D. Bobcat  ",
"Boscha  ",
"Bouncer Beagle  ",
"Bowler Hat Guy  ",
"Br'er Bear  ",
"Br'er Fox  ",
"Br'er Frog  ",
"Br'er Rabbit  ",
"Braddock  ",
"Bradley P.  Richfield  ",
"Bradley  Buttowski  ",
"Bradley Uppercrust III  ",
"Brett  ",
"Brittney Wong  ",
"Brudo Avarius  ",
"Bruno the Dog  ",
"Bruton  ",
"Brutus and Nero  ",
"Buck  ",
"Buck Cluck  ",
"Buck Leatherleaf  ",
"Bucky Bug  ",
"Bucky Oryx-Antlerson  ",
"Bucky the Squirrel  ",
"Buff Frog  ",
"Buford the Cook  ",
"Buford Van Stomm  ",
"Bugle Beagle  ",
"Bunsen Honeydew  ",
"Burger Beagle  ",
"Butch the Bulldog  ",
"Butcher Boy  ",
"Buzzie the Vulture  ",
"C[edit]  ",
"Cadpig  ",
"Calliope  ",
"Camilia Noceda  ",
"Camilia the Chicken  ",
"Candace Flynn  ",
"Candlehead  ",
"The Captain  ",
"Captain Amelia  ",
"Captain Bufo  ",
"Captain Grime  ",
"Captain Hook  ",
"Captain John Smith  ",
"Captain Phoebus  ",
"Carl the Robot  ",
"Carlotta the Maid  ",
"The Carpenter  ",
"Casey Junior  ",
"Cass Hamada  ",
"Cassandra/Cass  ",
"The Caterpillar  ",
"Catty the Elephant  ",
"Cedric the Sorcerer  ",
"Chaca  ",
"Chair Mouse  ",
"Chainsaw  ",
"Charlene Fiona Sinclair  ",
"Charlotte La Bouff  ",
"Cheetata and Cheetato  ",
"Chef Bouche  ",
"Chef Louis  ",
"Charles Muntz  ",
"Chernabog  ",
"Cheshire Cat  ",
"Chi-Fu  ",
"Chicha  ",
"Chicken Little  ",
"Chief  ",
"Chief Bogo  ",
"Chief Powhatan  ",
"Chien-Po  ",
"Chip  ",
"Chip Whistler  ",
"Chip Potts  ",
"Christopher Robin  ",
"Chuck  ",
"Cinderella  ",
"Circus Animals  ",
"Clank  ",
"Clara Cluck  ",
"Clarabelle Cow  ",
"Clarence Francis  Buttowski  ",
"Clayton  ",
"Cleo  ",
"Clio  ",
"Cloak and Dagger  ",
"Clopin Trouillefou  ",
"Clotho  ",
"Clover  ",
"The Coachman  ",
"Cobra Bubbles  ",
"Codfish  ",
"Cody  ",
"Cogsworth  ",
"Colette  ",
"The Colonel  ",
"Colonel Hathi  ",
"Commander Lyle Rourke  ",
"Commander Peepers  ",
"Cookie  ",
"Copper  ",
"Cornelius Robinson  ",
"Cousin Randy  ",
"Crane  ",
"Creeper  ",
"Cricket Green  ",
"Cri-Kee  ",
"The Crocodile (Tick Tock)  ",
"Cruella de Vil [a.k.a. De Vil]  ",
"Crumbelina DiCaramello  ",
"Cubby  ",
"Cyril Proudbottom  ",
"D[edit]  ",
"Daisy Duck  ",
"Dale  ",
"Dallben  ",
"Dandy (Jim) Crow  ",
"Danielle  ",
"Danny  ",
"Darby  ",
"Darling  ",
"Dash Parr  ",
"David Kawena  ",
"Deacon (Preacher) Crow  ",
"Delilah Dalmatian  ",
"Della Duck  ",
"Demetrius  ",
"Denahi  ",
"Dennis Avarius  ",
"Derek Blunt  ",
"DeSoto  ",
"Dewey  ",
"Dex Barrington  ",
"Diablo the Raven  ",
"Digger the Mole  ",
"Dijon the Thief  ",
"Dinah the Cat  ",
"Dinah the Dachshund  ",
"Dinky  ",
"Dipper Pines  ",
"The Director  ",
"Dixie  ",
"Dizzie the Vulture  ",
"Djali  ",
"Doc  ",
"Doctor Mouse  ",
"Dodger  ",
"The Dodo  ",
"The Dog Catcher  ",
"Doli  ",
"Dolly Dalmatian  ",
"Don Karnage  ",
"Donald Duck  ",
"Doofus Drake  ",
"The Doorknob  ",
"The Doorman  ",
"Dopey  ",
"Dopey (Straw Hat) Crow  ",
"Doris  ",
"The Dormouse  ",
"Double Dan  ",
"Doug Dalmatian  ",
"Doug Ramses  ",
"Dr. Calico  ",
"Dr. David Q. Dawson  ",
"Dr. Delbert Doppler  ",
"Dr. Facilier  ",
"Dr. Forrester  ",
"Dr. Heinz Doofenshmirtz  ",
"Dr. Jacques von Hämsterviel  ",
"Dr. Joshua Sweet  ",
"Dr. Jumba Jookiba  ",
"Dr. Reginald Bushroot  ",
"Dr. Teeth  ",
"Drake Mallard (Darkwing Duck)  ",
"Drew Lipsky / Dr. Drakken  ",
"Drizella Tremaine  ",
"Duchess  ",
"Duchess  ",
"Duckworth  ",
"Duke  ",
"Duke of Weselton  ",
"Duke Weaselton  ",
"Dumbo  ",
"Duncan  ",
"Dylan Dalmatian  ",
"E[edit]  ",
"Earl Sneed Sinclair  ",
"Eclipsa Butterfly  ",
"Ed  ",
"Edalyn  Clawthorne  ",
"Edgar Balthazar the Butler  ",
"Edric Blight  ",
"Edward  ",
"Eema  ",
"Eeyore  ",
"Einstein  ",
"El Capitan  ",
"Eli  La Bouff  ",
"Ellie Mae  ",
"Ellie Fredricksen  ",
"Elliott  ",
"Elmer Elephant  ",
"Elsa  ",
"Emira Blight  ",
"Emmitt Otterton  ",
"Emo Kid  ",
"Emperor Awesome  ",
"Emperor Belos  ",
"Emperor of China  ",
"The Enchantress  ",
"Esmeralda  ",
"Ethyl Hinkleman Phillips  ",
"Eudora  ",
"Eugene Fitzherbert  ",
"Evangeline  ",
"EVE  ",
"Evil Queen  ",
"Evinrude  ",
"F[edit]    ",
"Fa Li  ",
"Fa Zhou  ",
"Fagin  ",
"Fairy Godmother  ",
"Fairy Mary  ",
"Faline  ",
"Fall-Apart Rabbit  ",
"Faloo  ",
"Fat Cat  ",
"Father Wolf  ",
"Fats Crow  ",
"Fauna  ",
"Felicia the Cat  ",
"Felony  ",
"Fens  ",
"Fenton Crackshell (Gizmoduck)  ",
"Fenton Q. Harcourt  ",
"Ferb Fletcher  ",
"Ferdie Fieldmouse  ",
"Ferdinand the Bull  ",
"Ferguson O'Durguson  ",
"Fflewddur Fflam  ",
"Fidget  ",
"Fiddler Pig  ",
"Fife the Piccolo  ",
"Fifer Pig  ",
"Fifi the Featherduster  ",
"Figaro the Cat  ",
"Figment  ",
"Finnick  ",
"First Ancestor Fa  ",
"The Firebird  ",
"Fish Out of Water  ",
"Fix-It Felix",
 "Jr.  ",
"Flaps the Vulture  ",
"Flash  ",
"Flintheart Glomgold  ",
"Flit  ",
"Flora  ",
"Flotsam and Jetsam  ",
"Flounder  ",
"Flower  ",
"Flunkey the Baboon  ",
"Footman  ",
"Forte the Pipe Organ  ",
"Foxy Loxy  ",
"Fozzie Bear  ",
"Fran  ",
"Francis  ",
"Francis Johanna  Phillips Sinclair  ",
"Francois  ",
"Francois  ",
"Frank  ",
"Frankie the Frog  ",
"Franny Robinson  ",
"Fred  ",
"Friar Tuck  ",
"Friend Owl  ",
"Frou-Frou  ",
"G[edit]    ",
"Gadget Hackwrench  ",
"Gaetan  Moliére  ",
"Captain Gantu  ",
"Gaston  ",
"Gazelle  ",
"General Hologram  ",
"General Li  ",
"General Yunan  ",
"Genie  ",
"George Darling  ",
"Georges Hautecourt  ",
"Georgette  ",
"Geppetto  ",
"Giddy the Elephant  ",
"Gideon  ",
"Giselle  ",
"Gladstone Gander  ",
"Gliss  ",
"Glittering Goldie  ",
"Globgor Butterfly  ",
"Gloria Sato  ",
"Glossaryck  ",
"Gloyd Orangeboar  ",
"Go Go Tomago  ",
"Goob  ",
"Goofy  ",
"Goosey Loosey  ",
"Gopher  ",
"Gordie Gibble  ",
"Gosalyn Mallard  ",
"Governor John Ratcliffe  ",
"Grace  ",
"Gramma Alice  ",
"Gramma Tala  ",
"Gramps  ",
"Grand Councilwoman  ",
"The Grand Duke  ",
"Grandma Duck  ",
"Grandmother Fa  ",
"Grandmother Willow  ",
"Great Prince of the Forest  ",
"Grimsby  ",
"Grumpy  ",
"Grunkle Stan  ",
"Gunther Magnuson  ",
"Gurgi  ",
"Gus Lollygagger  ",
"Gus Goose  ",
"Gyro Gearloose  ",
"H[edit]    ",
"Hades  ",
"Hands  ",
"Hannibal McFist  ",
"Happy  ",
"Harold the Seahorse  ",
"Haroud Hazi Bin  ",
"Harold  Buttowski  ",
"Harvey Fenner  ",
"Headless Horseman  ",
"Heidi Weinerman  ",
"Heihei the Rooster  ",
"Hekapoo  ",
"Helga Sinclair  ",
"Hen Wen  ",
"Henry Fenner  ",
"Hera  ",
"Herb Muddlefoot  ",
"Hercules  ",
"Hermes  ",
"Hieronymus Bump  ",
"Hiram Flaversham  ",
"Hiro Hamada  ",
"Hit Cat the English Cat  ",
"Honey Lemon  ",
"Honker Muddlefoot  ",
"Hook Hand  ",
"Hoonah  ",
"Hooty  ",
"Hopediah Plantar  ",
"Horace  ",
"Horace & Jasper  ",
"Horace Horsecollar  ",
"The Horned King  ",
"Howard Handupme  ",
"Howard Weinerman  ",
"Huey  ",
"Hugo  ",
"Humbert the Huntsman  ",
"Humphrey the Bear  ",
"Hunter  ",
"Hyacinth Hippo  ",
"I[edit]    ",
"Iago  ",
"Ian the Alligator  ",
"Iandore  Lightfoot  ",
"Ichabod Crane  ",
"The Indian Big Chief  ",
"Iridessa  ",
"Imelda Rivera  ",
"Ivy Sundew  ",
")  ",
"J[edit]    ",
"J. Audubon Woodlore  ",
"J. Gander Hooter  ",
"J. Thaddeus Toad  ",
"J. Worthington Foulfellow  ",
"J.P. Spamley  ",
"Jack-in-the-Box  ",
"Jack Skellington  ",
"Jackie Lynn Thomas  ",
"Jackie Wackerman  ",
"Jackson  Hopscotch  ",
"Jafar  ",
"Jake  ",
"Jane Porter  ",
"Janna Ordonia  ",
"Jeb the Goat  ",
"Jennifer  Foxworth  ",
"Jenny Wren  ",
"Jeremy Birnbaum  ",
"Jerry Jumbeaux Jr.  ",
"Jesse the Ram  ",
"Jessica Rabbit  ",
"Jim Dear  ",
"Jim Hawkins  ",
"Jiminy Cricket  ",
"Jobless Joe  ",
"Jock  ",
"Joe Giraffe  ",
"Joey Hippo  ",
"John Darling  ",
"John Smith  ",
"John Silver  ",
"Johnny Appleseed  ",
"José Carioca  ",
"Jubileena Bing-Bing  ",
"Judge Claude Frollo  ",
"Judy Hopps  ",
"June  ",
"Junior  ",
"Junior the Buffalo  ",
"K[edit]    ",
"Kaa  ",
"Kala  ",
"Kanga  ",
"Kata  ",
"Katrina Van Tassel  ",
"Kekata the Medicine man  ",
"Kelly  ",
"Kenai  ",
"Kendall Perkins  ",
"Kerchak  ",
"Kermit the Frog  ",
"Kikimora  ",
"Kim Possible  ",
"The King  ",
"King  ",
"King Andrias Leviathan  ",
"The King of Hearts  ",
"King Candy/Turbo  ",
"King Eiddileg  ",
"King Hubert  ",
"King Kashekim Nedakh  ",
"King Leonidas  ",
"King Louie  ",
"King Richard  ",
"King Roland II  ",
"King Stefan  ",
"King Triton  ",
"Kirby  ",
"Kit Cloudkicker  ",
"KnowsMore  ",
"Kocoum  ",
"Koda  ",
"Kohut  ",
"Krebbs  ",
"Kristoff  ",
"Kron  ",
"Kronk Pepikrankenitz  ",
"Kuzco  ",
"L ",
"Lachesis  ",
"Lady  ",
"Lady Avarius  ",
"Lady Kluck  ",
"Lady Mouse  ",
"Lady Olivia  ",
"Lady Tremaine  ",
"Lafayette the Basset Hound  ",
"Lampwick  ",
"Larry the Duck  ",
"Lars  ",
"Launchpad McQuack  ",
"Laverne  ",
"Lawrence the Valet  ",
"Le Fou  ",
"Lefty  ",
"Lekmet  ",
"Leonard Helperman  ",
"Leopold Loggle  ",
"LePlume  ",
"Lewis  ",
"Li Shang  ",
"Lil Bad Wolf  ",
"Lil Lightning  ",
"Lilith Clawthorne  ",
"Lilo Pelekai  ",
"Ling  ",
"The Liquidator  ",
"Little Debbie  ",
"Little John  ",
"Little Toot  ",
"Mr. Litwak  ",
"Lizzy  ",
"Lizzy Griffiths  ",
"Lord Dominator  ",
"Lord Hater  ",
"Louie  ",
"Louie the Hot Dog Man  ",
"Louis the Alligator  ",
"Lucifer the Cat  ",
"Lucille Krunklehorn  ",
"Lucky  ",
"Lucky Jack  ",
"Ludo Avarius  ",
"Ludwig Von Drake  ",
"Luke  ",
"Lumière  ",
"Luz Noceda  ",
"M[edit]    ",
"Ma Beagle  ",
"Mabel Pines  ",
"Mad Hatter  ",
"Madame Adelaide Bonfamille  ",
"Madame Medusa  ",
"Madam Mim  ",
"Madame Upanova  ",
"Maddie Flour  ",
"Madellaine  ",
"Maggie  ",
"Magic Carpet  ",
"The Magic Mirror  ",
"Magica De Spell  ",
"Mahra the Baboon  ",
"Maid Marian  ",
"Major the Horse  ",
"Maleficent  ",
"Malina  ",
"Mama Heffalump  ",
"Mama Odie  ",
"Man the Hunter  ",
"Marahute  ",
"March Hare  ",
"Marco Diaz  ",
"Marcy Wu  ",
"Maria Media  ",
"Marie  ",
"Mariposa Diaz  ",
"Markowski  ",
"Marlon the Alligator  ",
"Mary Darling  ",
"Mary Poppins  ",
"The Matchmaker  ",
"Matriarch Elephant  ",
"Mattholomule  ",
"Maui  ",
"Maurice  ",
"Max Goof  ",
"Max Hare  ",
"Maximus  ",
"May  ",
"Mayor Lionheart  ",
"Mayor Toadstool  ",
"Mechanicles  ",
"Meeko  ",
"Megabyte Beagle  ",
"Megara  ",
"Megavolt  ",
"Melinda  ",
"Melpomene  ",
"Melvin  ",
"Mena  ",
"Merlin  ",
"Merlock the Magician  ",
"Merryweather  ",
"Mertle Edmonds  ",
"Meteora Butterfly  ",
"Michael Darling  ",
"Mickey Mouse  ",
"Mickey Mouse as Sorcerer’s Apprentice  ",
"Mike the Microphone  ",
"Mildred  ",
"Milo Murphy  ",
"Milo Thatch  ",
"Mina Loveberry  ",
"Mindy  ",
"Minnie Mouse  ",
"Minty Zaki  ",
"Mirage  ",
"Miranda Wright  ",
"Miss Bianca  ",
"Miss Kitty  ",
"Miss Nettle  ",
"Miss Piggy  ",
"Miss Skullnick  ",
"Mittens  ",
"Moana  ",
"Mochi  ",
"Moley  ",
"Molly Cunningham  ",
"Monica Devertebrae  ",
"Monsieur D'Arque  ",
"Monstro  ",
"Monterey Jack  ",
"Moon Butterfly  ",
"Morcupine Porcupine  ",
"Morgana  ",
"Morgana McCawber  ",
"Morph  ",
"Mortimer Mouse  ",
"Morty Fieldmouse  ",
"Mother Gothel  ",
"Mother Rabbit  ",
"Mouth  ",
"Mowgli  ",
"Mozenrath  ",
"Mr. Arrow  ",
"Mr. Big  ",
"Mr. Flour  ",
"Mr. Jolly  ",
"Mr. Lizard  ",
"Mr. Pettibone  ",
"Mr. Pulman  ",
"Mr. Smee  ",
"Mr. Snoops  ",
"Mr. Stork  ",
"Mr. Willerstein  ",
"Mr. Woolensworth  ",
"Mr. Yama  ",
"Mrs. Calloway  ",
"Mrs. Featherby  ",
"Mrs. Hasagawa  ",
"Mrs. Judson  ",
"Mrs. Jumbo  ",
"Mrs. Otterton  ",
"Mrs. Possum  ",
"Mrs. Potts  ",
"Mrs. Quail  ",
"Ms. Chicarelli  ",
"Mufasa  ",
"Mulan  ",
"Mungo  ",
"Mushu  ",
"N[edit]    ",
"Nakoma  ",
"Nala  ",
"Nana  ",
"Nancy Green  ",
"Nancy Tremaine  ",
"Nani Pelekai  ",
"Nanny  ",
"Napoleon the Bloodhound  ",
"Nasira  ",
"Nathaniel  ",
"Ned  ",
"Ned the Baboon  ",
"Neera  ",
"NegaDuck  ",
"Nemo  ",
"Nessus  ",
"Nibs  ",
"Nicholas P. Wilde  ",
"Nita  ",
"Nurse Mouse  ",
"Nutsy the Vulture  ",
"O[edit]    ",
"Oaken  ",
"The Octopus  ",
"Officer Keys  ",
"Olaf  ",
"Oliver  ",
"Olivia Flaversham  ",
"Ollie the Pig  ",
"Omnitraxus Prime  ",
"Onus  ",
"Orange Bird  ",
"Orddu  ",
"Orgoch  ",
"Ortensia  ",
"Orville  ",
"Orwen  ",
"Oskar Greason  ",
"Oswald the Lucky Rabbit  ",
"Otto  ",
"Owl  ",
"P[edit]    ",
"Pacha  ",
"Pain and Panic  ",
"Panchito Pistoles  ",
"Pantsy  ",
"Pascal  ",
"Patch  ",
"Pearl Gesner  ",
"Peg  ",
"Peg Pete  ",
"Pegasus  ",
"Penguin Waiters  ",
"Penn Zero  ",
"Penny  ",
"Penny  ",
"Penny  ",
"Penny's Mom  ",
"Pepper Ann Pearson  ",
"Peppo the Italian Cat  ",
"Percival C. McLeach  ",
"Percy  ",
"Perdita  ",
"Periwinkle  ",
"Perry Potter  ",
"Perry the Platypus  ",
"Pete  ",
"Pete Junior  ",
"Peter Pan  ",
"Peter Pig  ",
"The Phantom Blot  ",
"Philoctetes  ",
"Philippe the Horse  ",
"Phineas Flynn  ",
"Piglet  ",
"Pinocchio  ",
"Pip  ",
"Pistol Pete  ",
"Plio  ",
"Pluto  ",
"Pocahontas  ",
"Poe De Spell  ",
"Polly Petunia Plantar  ",
"Pom-Pom  ",
"Pongo  ",
"Pony Head  ",
"Powerline  ",
"Practical Pig  ",
"Preston B. Whitmore  ",
"Pretty Boy  ",
"Prince  ",
"Prince Charming  ",
"Prince Edward  ",
"Prince Eric  ",
"Prince Hans  ",
"Prince James  ",
"Prince John  ",
"Prince Naveen  ",
"Prince Phillip  ",
"Princess  ",
"Princess Amber  ",
"Princess Eilonwy  ",
"Princess Jasmine  ",
"Princess Kidagakash  ",
"Principal Mazur  ",
"Principal Skeeves  ",
"Prissy the Elephant  ",
"Professor Abominable  ",
"Professor Norton Nimnul  ",
"Professor Ratigan  ",
"Pronk Oryx-Antlerson  ",
"Prudence  ",
"Pua  ",
"Pumbaa  ",
"Pyro  ",
"Q[edit]    ",
"Quackerjack  ",
"Quasimodo  ",
"Queen  ",
"Queen Clarion  ",
"Queen Grimhilde  ",
"Queen Leah  ",
"Queen Miranda  ",
"Queen Mousetoria  ",
"Queen Narissa  ",
"The Queen of Hearts  ",
"R[edit]    ",
"Rabbit  ",
"Rachel  ",
"Rafael Diaz  ",
"Rafiki  ",
"Rajah  ",
"Rancis Fluggerbutter  ",
"Randall Cunningham  ",
"Rapunzel  ",
"Rashida Remington  ",
"Ratigan  ",
"Ratty  ",
"Ray the Firefly  ",
"Razoul  ",
"Rebecca Cunningham  ",
"Red  ",
"Remy Remington  ",
"Reuben (Experiment 625)  ",
"Rhino  ",
"Rhoda Dendron  ",
"Rhombulus  ",
"Rico  ",
"The Ringmaster  ",
"Rita  ",
"River Butterfly  ",
"Rizzo the Rat  ",
"Robert Zimuruski  ",
"Robert Mark Sinclair  ",
"Robin Hood  ",
"Robin the Frog  ",
"Roger Rabbit  ",
"Roger Radcliffe  ",
"Rolly  ",
"Ronaldo  ",
"Ron Stoppable  ",
"Roo    ",
"Roquefort the Mouse  ",
"Roscoe  ",
"The Rose  ",
"Rosetta  ",
"Rowlf the Dog  ",
"Roxanne  ",
"Roy Danger Hess  ",
"Ruby  ",
"Rufus  ",
"Runt of the Litter  ",
"Russell Remington  ",
"Rusty the Dog  ",
"Rutt and Tuke  ",
"S[edit]    ",
"Sisu  ",
"Sadie Croaker  ",
"Sadira  ",
"Sally ragdoll  ",
"Sam Flynn  ",
"Sam the Sheriff  ",
"Samson the Horse  ",
"Sarabi  ",
"Sarafina  ",
"Sarah Hawkins  ",
"Sarousch  ",
"Sasha Waybright  ",
"Sashi Kobayashi  ",
"Scar  ",
"Scat Cat  ",
"Scooter  ",
"Scratchy  ",
"Scrooge McDuck  ",
"Scroop  ",
"Scuttle  ",
"Sebastian  ",
"Secretary Bird  ",
"Sensei Brantley  ",
"Sergeant Calhoun  ",
"Sgt. Tibbs  ",
"Shan Yu  ",
"Shank  ",
"Shanti (The Girl)  ",
"Sha-ron  ",
"Shego  ",
"Shenzi  ",
"Shere Khan  ",
"Sheriff of Nottingham  ",
"Shun Gon the Chinese Cat  ",
"Si & Am  ",
"Sidney Tiberius  Turtlepuss  ",
"Silvermist  ",
"Simba    ",
"Sir Ector  ",
"Sir Giles  ",
"Sir Hiss  ",
"Sir Kay  ",
"Sir Pellinore  ",
"Sis Bunny  ",
"Sitka  ",
"Skara  ",
"Skeeter  ",
"Skippy Bunny  ",
"Sleepy  ",
"Slightly  ",
"Smolder the Bear  ",
"Sneezy  ",
"Snow White  ",
"Snowanna Rainbeau  ",
"Princess Sofia  ",
"Soggy Joe  ",
"Sorcerer’s Apprentice  ",
"Sour Bill  ",
"Sparky  ",
"Sparky (Experiment 221)  ",
"Sparky  ",
"Specks (Glasses) Crow  ",
"Speedy the Snail  ",
"Spike  ",
"Spot  ",
"Spot Helperman/Scott Leadready II  ",
"Sprig Plantar  ",
"Spring Sprite  ",
"Squeaks the Caterpillar  ",
"Stabbington brothers  ",
"Star Butterfly  ",
"Statler and Waldorf  ",
"Steelbeak  ",
"Stitch  ",
"Stromboli  ",
"Stu Hopps  ",
"Stumpy  ",
"The Sultan  ",
"Sultan the Footstool  ",
"Suri  ",
"Sven  ",
"Swedish Chef  ",
"Sweetums  ",
"Swizzle Malarkey  ",
"Sykes  ",
"Sylvia  ",
"Sylvia Marpole  ",
"Sylvia Sundew  ",
"T[edit]    ",
"Tadashi Hamada  ",
"Taffyta Muttonfudge  ",
"Tagalong Bunny  ",
"Tamatoa  ",
"Tanana  ",
"Tank  ",
"Tank Muddlefoot  ",
"Tantor  ",
"Tantor's Mother  ",
"Taran  ",
"Tarzan    ",
"Taurus Bulba  ",
"Ted Betterhead  ",
"Terence  ",
"Terk  ",
"Terpsichore  ",
"Thalia  ",
"Thomas  ",
"Thomas O'Malley  ",
"Thug  ",
"Thumper  ",
"Thumper's Mother  ",
"Thunderbolt  ",
"Tiana  ",
"Tibblet-Tibblie Grimmhammer III  ",
"Tiger Lily  ",
"Tigger  ",
"Tillie Tiger  ",
"Tilly Green  ",
"Timon  ",
"Timothy Q. Mouse  ",
"Tina  ",
"Tinker Bell  ",
"Tino Tonitini  ",
"Tiny  ",
"Tiny Nose  ",
"Tip  ",
"Tipo  ",
"Tito  ",
"Toadie  ",
"Tobias the Reluctant Dragon  ",
"Toby the Dog  ",
"Toby Tortoise  ",
"Toby Turtle  ",
"Tod  ",
"Toffee  ",
"Tom  ",
"Tom Lucitor  ",
"Tootles  ",
"Toots  ",
"Toulouse  ",
"Tramp  ",
"Travis  ",
"Trigger the Vulture  ",
"Trusty  ",
"Tug  ",
"Tui  ",
"Turkey Lurkey  ",
"Tuskernini  ",
"Tuti  ",
"Tweedledum and Tweedledee  ",
"Two Fingers  ",
"U[edit]  ",
"Character  ",
"Uncle Art  ",
"Uncle Waldo  ",
"Url  ",
"Ursula  ",
"V[edit]    ",
"Vanellope von Schweetz  ",
"Vanessa (The Little Mermaid)  ",
"Varian  ",
"Vazquez  ",
"Veteran Cat  ",
"Victor  ",
"Vidia  ",
"Vincenzo  Santorini  ",
"Violet Parr  ",
"Vixey  ",
"Vladimir Goudenov Grizzlikof  ",
"Vanessa Doofenshmirtz  ",
"W[edit]    ",
"Waffles  ",
"Wahn  ",
"Walliam  Ribbiton  ",
"The Walrus  ",
"Wander  ",
"Warden Wrath  ",
"Wasabi  ",
"Webby Vanderquack  ",
"Wendy Darling  ",
"Wesley  ",
"White Rabbit  ",
"Widow Tweed  ",
"Wiggins  ",
"Wilbur  ",
"Wilbur Robinson  ",
"Wilhelmina Packard  ",
"Willie the Giant  ",
"Willow Park  ",
"Winifred the Elephant  ",
"Winkie the Barman  ",
"Winnie the Pooh  ",
"Winston  ",
"Witherspoon  ",
"Woolter the Ram  ",
"Wormwood the Raven  ",
"Wreck-It Ralph  ",
"Wynchel  ",
"X[edit]  ",
"XR  ",
"Y[edit]  ",
"Yao  ",
"Yar  ",
"Yax  ",
"Yen Sid  ",
"Yesss  ",
"Yo-Yo  ",
"Yzma  ",
"Z[edit]  ",
"Zazu  ",
"Zeus  ",
"Ziggy the Vulture  ",
"Zini  ",
"Zipper "};
    }
}